import BriefGenerator from "@/components/BriefGenerator";

export default function Home() {
  return (
    <div className="flex flex-1 flex-col">
      <header className="border-b border-sand px-6 py-10 text-center">
        <h1 className="font-serif text-5xl font-medium tracking-[0.35em] pl-[0.35em]">
          PRISM
        </h1>
        <p className="mt-3 text-[11px] uppercase tracking-[0.3em] text-ink-soft">
          AI VIP Brief Generator
        </p>
      </header>

      <main className="mx-auto w-full max-w-6xl flex-1 px-6 py-12">
        <BriefGenerator />
      </main>

      <footer className="border-t border-sand px-6 py-6 text-center text-[11px] uppercase tracking-[0.2em] text-ink-soft">
        Briefs are generated by AI from the information you provide. Verify before use.
      </footer>
    </div>
  );
}
